CoreMongo.Web/ViewModels/ErrorViewModel.cs
using System;

namespace CoreMongo.Web.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreMongo.Web/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreMongo.Web.Domain.Models;
using CoreMongo.Web.Domain.Services;

namespace CoreMongo.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoriaService _categoriaService;

        public CategoriaController(ICategoriaService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public IActionResult Index()
        {
            return View(_categoriaService.List());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Categoria());
        }

        [HttpPost]
        public IActionResult Create(Categoria obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            _categoriaService.Add(obj);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var obj = _categoriaService.FindById(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(Categoria obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            _categoriaService.Update(obj);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            var obj = _categoriaService.FindById(id);

            if (obj == null)
            {
                return NotFound();
            }

            _categoriaService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

CoreMongo.Web/Controllers/DespesaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreMongo.Web.Domain.Models;
using CoreMongo.Web.Domain.Services;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreMongo.Web.Controllers
{
    public class DespesaController : Controller
    {
        private readonly IDespesaService _despesaService;
        private readonly ICategoriaService _categoriaService;

        public DespesaController(IDespesaService despesaService, ICategoriaService categoriaService)
        {
            _despesaService = despesaService;
            _categoriaService = categoriaService;
        }

        public IActionResult Index()
        {
            return View(_despesaService.List());
        }

        [HttpGet]
        public IActionResult Create()
        {
            //PopulateDropDowns();
            return View(new Despesa());
        }

        [HttpPost]
        public IActionResult Create(Despesa obj)
        {
            if (!ModelState.IsValid)
            {
                //PopulateDropDowns();
                return View(obj);
            }

            _despesaService.Add(obj);

            //return RedirectToAction("Index");
            return View(obj);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var obj = _despesaService.FindById(id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(Despesa obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            _despesaService.Update(obj);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(string id)
        {
            var obj = _despesaService.FindById(id);

            if (obj == null)
            {
                return NotFound();
            }

            _despesaService.Remove(id);

            return RedirectToAction("Index");
        }

        private void PopulateDropDowns()
        {
            ViewBag.Categorias = _categoriaService.List().Select(x=> new SelectListItem(x.Descricao, x.ID));
        }
    }
}

CoreMongo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreMongo.Web.ViewModels;

namespace CoreMongo.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreMongo.Web/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreMongo.Web.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreMongo.Web.Controllers
{
    public class PedidoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Pedido());
        }

        [HttpPost]
        public IActionResult Create(Pedido pedido)
        {
            return View(pedido);
        }
    }
}

CoreMongo.Web/ViewComponents/CategoriaViewComponent.cs
using CoreMongo.Web.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMongo.Web.ViewComponents
{
    public class CategoriaViewComponent : ViewComponent
    {
        private readonly ICategoriaService _categoriaService;
        public CategoriaViewComponent(ICategoriaService categoriaService)
        {
            _categoriaService = categoriaService;
        }

        public IViewComponentResult Invoke(string selectedID)
        {
            return View(_categoriaService.List().Select(x => new SelectListItem(x.Descricao, x.ID, x.ID ==selectedID)));
        }
    }
}

CoreMongo.Web/Views/Categoria/Create.cshtml
@model CoreMongo.Web.Domain.Models.Categoria

@{
    ViewData["Title"] = "Inserir";
}

<h1>Inserir</h1>

<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Inserir">
            @*<partial name="_cadastro" />*@
            
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control" />
                @*<span asp-validation-for="Descricao" class="text-danger"></span>*@
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMongo.Web/Views/Categoria/Edit.cshtml
@model CoreMongo.Web.Domain.Models.Categoria

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group d-none">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMongo.Web/Views/Categoria/Index.cshtml
@model IEnumerable<CoreMongo.Web.Domain.Models.Categoria>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th style="width: 65%">
                Descrição
            </th>
            <th style="width: 10%">
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th style="width: 15%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.Ativo, "_SimNaoTemplate")*@
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>

CoreMongo.Web/Views/Despesa/Create.cshtml
@model CoreMongo.Web.Domain.Models.Despesa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Despesa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" type="date" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" type="number" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantidadeParcelas" class="control-label"></label>
                <input asp-for="QuantidadeParcelas" class="form-control" type="number" />
                <span asp-validation-for="QuantidadeParcelas" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pago" /> @Html.DisplayNameFor(model => model.Pago)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaID" class="control-label"></label>
                @*<input asp-for="CategoriaID" class="form-control" />*@
                @*<select asp-for="CategoriaID" asp-items="ViewBag.Categorias">
                        <option>Selecione</option>
                    </select>*@

                <select asp-for="CategoriaID" class="form-control">
                    <vc:categoria selected-id="@Model.CategoriaID"></vc:categoria>
                </select>
                <span asp-validation-for="CategoriaID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMongo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreMongo.Web/Views/Pedido/Create.cshtml
@using CoreMongo.Web.Util
@model CoreMongo.Web.Domain.Models.Pedido

<h4>Pedido</h4>
<hr />

<form asp-action="Create">
    <input type="hidden" value="@Model.ToJson()" disabled id="object" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-8 form-group">
            <label asp-for="Descricao" class="control-label">Descrição</label>
            <input asp-for="Descricao" class="form-control" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
        <div class="col-md-4 form-group">
            <label asp-for="Data" class="control-label"></label>
            <input asp-for="Data" class="form-control" type="date" />
            <span asp-validation-for="Data" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 form-group">
            <label class="control-label">Produto</label>
            <input class="form-control" id="txtProdutoID" />
        </div>
        <div class="col-md-3 form-group">
            <label class="control-label">Valor</label>
            <input class="form-control" id="txtValor" />
        </div>
        <div class="col-md-3 form-group">
            <label class="control-label">Observação</label>
            <input class="form-control" id="txtObservacao" />
        </div>
        <div class="col-md-3">
            <label class="control-label">&nbsp;</label>
            <button type="button" class="form-control btn btn-primary" onclick="AdicionarItem();">Adicionar Item</button>
        </div>
    </div>

    <div class="row @(Model.Itens.Any() ? "" : "d-none")" id="divItens">
        <div class="col-md-12 form-group small" id="tbItens">
            <table class="table">
                <thead>
                    <tr>
                        <td>Produto</td>
                        <td>Valor</td>
                        <td>Observação</td>
                        <td>Ações</td>
                    </tr>
                </thead>
                <tbody>
                    @*@for (int i = 0; i < Model.Itens.Count; i++)
                        {
                            <tr>
                                <td>
                                    <input type="hidden" name="Itens.Index" value="@i" />
                                    <input type="hidden" asp-for="Itens[i].ProdutoID" />
                                    <input type="hidden" asp-for="Itens[i].Valor" />
                                    <input type="hidden" asp-for="Itens[i].Observacao" />
                                    @Model.Itens[i].ProdutoID
                                </td>
                                <td>
                                    @Model.Itens[i].Valor
                                </td>
                                <td>
                                    @Model.Itens[i].Observacao
                                </td>
                                <td>
                                    <button type="button" class="btn btn-danger" onclick="Excluir(this);">Excluir</button>
                                </td>
                            </tr>
                        }*@
                </tbody>
            </table>
        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
    $(function () {
        let obj = JSON.parse($("#object").val());

        obj.Itens.forEach(ListarItem);
    })

    function Excluir(el) {
        $(el).closest("tr").remove();

        if (!$("#tbItens tbody tr").length) {
            $("#divItens").addClass("d-none");
        }
    }

    function AdicionarItem() {
        let produtoID = document.getElementById("txtProdutoID").value;
        let valor = document.getElementById("txtValor").value;
        let observacao = document.getElementById("txtObservacao").value.trim();

        if (!produtoID) {
            alert("É necessário informar um produto");
            return;
        }

        ListarItem({
            ProdutoID: produtoID,
            Valor: valor,
            Observacao: observacao
        });
    }

    function ListarItem(item) {
        let id = NewID();

        let row = '<tr>';
        row += '<td>';
        row += '<input type="hidden" name="Itens.Index" value="' + id + '"/>';
        row += '<input type="hidden" name="Itens[' + id + '].ProdutoID" value="' + item.ProdutoID + '"/>';
        row += '<input type="hidden" name="Itens[' + id + '].Valor" value="' + item.Valor + '"/>';
        row += '<input type="hidden" name="Itens[' + id + '].Observacao" value="' + item.Observacao + '"/>' + item.ProdutoID + '</td>';
        row += '<td>' + item.Valor + '</td>';
        row += '<td>' + item.Observacao + '</td>';
        row += '<td><button type="button" class="btn btn-danger" onclick="Excluir(this);">Excluir</button></td>';
        row += '</tr>';

        $("#tbItens tbody").append(row);
        $("#divItens").removeClass("d-none");
    }

    function NewID () {
        // Math.random should be unique because of its seeding algorithm.
        // Convert it to base 36 (numbers + letters), and grab the first 9 characters
        // after the decimal.
        //return '_' + Math.random().toString(36).substr(2, 9);

        return '_' + (new Date().getUTCMilliseconds().toString() + new Date().getTime().toString()).toString();
    };
    </script>
}

CoreMongo.Web/Views/Shared/Components/Categoria/Default.cshtml
@model IEnumerable<SelectListItem>

<option value="">Selecione</option>

@foreach (var item in Model)
{
    @if (item.Selected)
    {
        <option value="@item.Value" selected>@item.Text</option>
    }
    else
    {
        <option value="@item.Value">@item.Text</option>
    }
}

CoreMongo.Web/Views/Shared/DisplayTemplates/_SimNaoTemplate.cshtml
@(Model? "Sim": "Não")

CoreMongo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreMongo.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreMongo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Despesa" asp-action="Create">Despesas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Create">Pedidos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CoreMongo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*@if (ViewBag.Sucesso == true)
    {
        <div  id="teste" class="toast alert-success" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header alert-success">
                Operação realizada com sucesso!
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>

        <script>
                $(function () {
                    $('.toast').toast({
                        delay: 2000
                    });
                    
                    $('.toast').toast("show");
                });
        </script>
    }*@

    @RenderSection("Scripts", required: false)
</body>
</html>